class AppVocabularies {
  /// Map associating modelType integers with their respective training vocabularies
  static final Map<int, List<String>> modelVocabs = {
    // modelType = 0: quartznet
    0: [' ', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'ŋ', 'ɔ', 'ɛ', 'ɲ'],

    // modelType = 1: soloni
    1: [
      '<unk>', '<pad>', '▁k', '▁b', '▁n', 'an', '▁y', '▁d', '▁ka', '▁s', '▁[',
      '▁m', '▁f', 'la', '▁t', 'in', '▁ye', '▁bɛ', '▁a', '▁la', 'ɔn', '?]', '▁o',
      'ra', '▁[?]', 'ɛn', 'ɔr', '▁kɛ', 'aa', 'cs', '▁na', 'un', 'ɔrɔ', 'en',
      '▁an', '▁i', 'ɔg', 'li', '▁ko', 'um', '▁j', '▁ni', 'ɛr', 'ana', '▁ɲ',
      '▁ma', '▁min', '▁c', '▁w', 'ɛrɛ', '▁se', 'ya', 'ɔgɔ', '▁de', '▁fɔ', '▁dɔ',
      'on', '▁yɛrɛ', '▁kɔn', 'am', '▁bi', 'is', '▁u', '▁sɔrɔ', 'lo', '▁be',
      'len', '▁ne', 'aara', '▁tɛ', 'ri', '▁fɛn', 'ig', 'go', 'lu', 'ba', 'nu',
      '▁nin', '▁don', '▁kan', '▁baara', 'le', 'ga', '▁wa', '▁taa', '▁ta', 'ug',
      '▁mɔgɔ', 'olo', '▁ba', '▁in', '▁bɛɛ', '▁bɔ', '▁sa', 'ogo', 'kɛ', '▁kun',
      '▁fɛ', 'igi', '▁mun', '▁kɔnɔ', '▁di', 'ma', '▁e', 'lan', '▁yɔrɔ', '▁den',
      '▁h', 'ur', '▁fa', '▁olu', '▁dɔw', 'ugu', 'lɔ', '▁fana', 'so', '▁kɔ',
      'gɛ', 'uma', 'aman', '▁si', '▁da', 'ɔgɔn', '▁yen', '▁san', '▁fi', 'lɛ',
      '▁ha', '▁ɲɛ', 'elen', 'ti', 'na', 'ɛb', '▁cogo', 'uru', '▁bolo', '▁caman',
      '▁kelen', 'ini', '▁ti', 'ura', '▁fo', '▁dɔn', 'ka', 'ɛnɛ', '▁ɲɔgɔn',
      '▁bana', '▁cɛ', '▁kɔni', '▁to', '▁p', 'si', '▁man', 'sa', 'fɛ', 'ɛbɛ',
      'mɛ', '▁fura', 'ɔna', 'sɛbɛ', '▁kuma', 'bu', '▁ja', 'ama', '▁fɛnɛ',
      '▁bila', '▁kosɛbɛ', '▁ale', '▁mu', '▁ninnu', '▁kɔnɔna', 'se', 'ise',
      '▁ji', '▁ki', 'no', 'noise', 'ki', '▁sis', '▁dɛ', '[?]', '▁minnu',
      '▁sigi', '▁kalan', '▁sisan', 'inɛ', '▁so', '▁g', 'fa', '▁saba', '▁te',
      'jɛ', 'ni', '▁fɔlɔ', 'ko', 'ro', '▁yan', 'ɔrɔn', '▁gɛ', 'ɛna', '▁ca',
      '▁kɔrɔ', '▁wɛrɛ', '▁ban', '▁nana', '▁nɔ', '▁wari', 'da', '▁muso',
      '▁fara', '▁hali', 're', '▁ani', 'oli', 'ɲɛ', '▁sɛnɛ', 'ke', '▁tun',
      '▁pa', '▁nɔgɔ', '▁waa', '▁lajɛ', '▁du', '▁dugu', 'ɛgɛ', '▁fan', 'bi',
      '▁gɛlɛ', 'igɛ', 'yi', '▁yi', '▁dɔgɔ', 'den', '▁nun', 'kolo', '▁dɔrɔn',
      '▁mɔgɔw', 'ee', '▁kɛra', 'olu', '▁fila', 'uni', '▁gɛlɛya', '▁jɔ',
      'isɛn', '▁tan', '▁jam', '▁bɛn', 'mi', 'mu', '▁munnu', '▁waati', '▁aw',
      'uman', '▁minɛ', '▁mɛ', '▁dun', '▁jamana', 'kan', 'mɔgɔ', '▁ga',
      '▁sira', '▁dam', 'kili', '▁dɔɔn', '▁bon', 'man', '▁ala', '▁dan', 'seke',
      '▁ɔ', '▁tɔ', 'eere', 'te', 'ɛlɛ', '▁mana', '▁tigi', '▁tigɛ', '▁feere',
      '▁nunnu', '▁bin', 'nin', 'tɔ', 'ta', '▁kɛnɛ', 'isa', '▁daminɛ', 'misɛn',
      '▁nafa', '▁anw', '▁taara', '▁ɛ', 'gati', 'yɔrɔ', '▁ɲɛna', '▁wu',
      '▁ɲini', '▁paseke', 'inin', 'iya', '▁ya', '▁kana', 'gan', 'tɔrɔ', 'ele',
      '▁kɔfɛ', 'ku', 'kɛla', '▁ten', '▁wagati', '▁wala', 'isi', '▁jate',
      '▁sɔn', '▁furakɛ', '▁lab', '▁bɛna', '▁sen', '▁kɔlɔ', '▁tɛmɛ', '▁jɛ',
      '▁ŋ', '▁joli', '▁sababu', '▁foro', 'lon', '▁denmisɛn', 'kɔ', '▁tu',
      '▁wo', '▁fari', '▁sugu', '▁hakɛ', 'kun', '▁dɔgɔtɔrɔ', 'gin', '▁hakili',
      '▁do', '▁faa', '▁ku', '▁fini', 'ani', 'nen', '▁maa', 'ale', '▁kalo',
      'di', '▁nka', '▁cogoya', 'baga', 'yɛn', '▁sera', '▁mi', '▁yɛlɛ',
      '▁sara', '▁sin', 'tigi', '▁tug', 'ji', 'ɛbɛn', '▁ci', '▁bagan', '▁dum',
      'kɔrɔ', '▁sɛ', '▁kama', '▁kile', '▁sɛbɛn', '▁jum', '▁ɲuman', 'lima',
      '▁faamu', '▁mara', '▁yiri', 'fɛn', '▁cɛn', '▁su', '▁jumɛn', 'isɛ',
      '▁foyi', 'fɔ', '▁kɔlɔlɔ', '▁kala', '▁bɔra', '▁ɲa', '▁kila', '▁sabu',
      '▁duuru', 'igin', 'wu', '▁suma', '▁gi', '▁dumuni', '▁dɛmɛ', 'risa',
      '▁walasa', '▁kɛr', '▁deg', 'su', '▁ɛɛ', '▁wuli', '▁segin', 'to', 'wa',
      'ina', '▁furu', '▁wele', '▁kɛnɛya', 'pa', '▁dɔɔnin', '▁jigin', 'minɛ',
      '▁caya', '▁tɔgɔ', '▁jan', '▁denmisɛnnin', 'cogo', '▁yira', 'gɛn',
      '▁furakɛli', '▁boli', 'bɔ', '▁taga', '▁ɲinin', '▁sɛgɛ', 'ɲini', 'dɔn',
      '▁tuguni', 'fin', '▁kɛlɛ', '▁dɔɔni', '▁ɲi', '▁naani', 'sin', '▁sanfɛ',
      'ɔnɔ', '▁kɛmɛ', '▁jateminɛ', '▁mɛn', '▁bu', '▁filɛ', '▁jugu', '▁minɛn',
      'liya', 'ye', '▁kara', '▁tile', '▁misi', 'yɛ', '▁farikolo', '▁sabula',
      '▁deli', '▁dilan', 'bolo', '▁fanga', '▁kɛlen', 'dama', 'iri', '▁karisa',
      '▁dugukolo', '▁ŋa', 'mɔgɔw', '▁sɔgɔ', '▁le', '▁tiɲɛ', '▁', 'a', 'n',
      'i', 'ɛ', 'k', 'ɔ', 'e', 'b', 'o', 'l', 'u', 's', 'm', 'y', 'r', 'd',
      "'", 'f', 't', '[', ']', 'g', 'w', 'c', '?', 'j', 'ɲ', 'h', 'p', 'ŋ',
      'z', '-', 'v', 'q', 'é', '0', 'ô', '4', 'à', 'x', 'è', 'ù', '.', '1',
      '8', 'S'
    ],

    // modelType = 2: SLUModel
    2 : ['<unk>', '<s>', '</s>', '<pad>', "▁'", 'ti', "':", "',", 'en', 'on', 'tion',
      'er', "'", '▁', 't', 'e', 'i', 'a', 'n', 'o', ':', 'r', 'c', 's', ',', 'p', '_', '{',
      '}', '[', ']', 'g', 'l', 'f', 'O', 'u', 'm', 'N', 'v', 'y', 'M', 'H', 'b', 'P', 'd', 'q', 'A', 'F', 'Q', 'h'],
  };
}